// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmvPwC8J3e84lRW8MdH_tFLkVuyNvFQU',
    appId: '1:958431963176:web:fdcd97d71b4b12af9ead1d',
    messagingSenderId: '958431963176',
    projectId: 'digitalmenu-c51d2',
    authDomain: 'digitalmenu-c51d2.firebaseapp.com',
    storageBucket: 'digitalmenu-c51d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_GOCbdYj_u5LC-anxtjYWbWM6iA4HqA',
    appId: '1:958431963176:android:222b76db8a5a4a0f9ead1d',
    messagingSenderId: '958431963176',
    projectId: 'digitalmenu-c51d2',
    storageBucket: 'digitalmenu-c51d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowG4jegNMg89bDVtHSX_7NMuFFc47sTw',
    appId: '1:958431963176:ios:41057564541812419ead1d',
    messagingSenderId: '958431963176',
    projectId: 'digitalmenu-c51d2',
    storageBucket: 'digitalmenu-c51d2.appspot.com',
    iosBundleId: 'com.example.digitalMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCowG4jegNMg89bDVtHSX_7NMuFFc47sTw',
    appId: '1:958431963176:ios:41057564541812419ead1d',
    messagingSenderId: '958431963176',
    projectId: 'digitalmenu-c51d2',
    storageBucket: 'digitalmenu-c51d2.appspot.com',
    iosBundleId: 'com.example.digitalMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmvPwC8J3e84lRW8MdH_tFLkVuyNvFQU',
    appId: '1:958431963176:web:b094d7e2f04b77e49ead1d',
    messagingSenderId: '958431963176',
    projectId: 'digitalmenu-c51d2',
    authDomain: 'digitalmenu-c51d2.firebaseapp.com',
    storageBucket: 'digitalmenu-c51d2.appspot.com',
  );

}